Heavy message handling 5041
elasticio/sailor-nodejs pull request #170
Opened 2021-01-25 11:37 UTC by irisked

2021-01-25 12:14 UTC, VitaliyKovalchuk approved these changes

2021-01-25 13:10 UTC, VitaliyKovalchuk commented on package.json
> +    "@elastic.io/object-storage-client": "0.0.4-dev1",
so why to not use the latest version?

2021-01-25 16:33 UTC, A3a3e1 requested changes
Well done 👍 
Please also don't forget to update the Changelog file

2021-01-27 16:17 UTC, A3a3e1 approved these changes

2021-01-27 16:17 UTC, merged