Consume messages instead of get
elasticio/sailor-nodejs pull request #178
Opened 2021-06-09 08:17 UTC by PaulAnnekov

https://github.com/elasticio/elasticio/issues/5432

2021-06-10 10:47 UTC, zuker approved these changes

2021-06-15 12:41 UTC, HannaTrotsenko requested changes

2021-06-15 12:41 UTC, HannaTrotsenko commented on package.json
> +  "version": "2.6.24-consumer-with-reconnect",
Version should be increased by 1 at patch number `2.6.25-consumer-with-reconnect`

2021-06-15 12:44 UTC, HannaTrotsenko commented on package.json
> +  "version": "2.6.24-consumer-with-reconnect",
and the final version should be 2.6.25 😉

2021-06-17 14:09 UTC, HannaTrotsenko approved these changes

2021-06-17 14:21 UTC, merged