#6233 fix sailor ignores error from maester; update test
elasticio/sailor-nodejs pull request #191
Opened 2022-06-09 08:28 UTC by Allirey

[#6233](https://github.com/elasticio/elasticio/issues/6233)

2022-06-10 14:43 UTC, PaulAnnekov requested changes
You also need to update .circleci/config.yaml, to make it run `npm run audit` instead of `npm audit ...`.

2022-06-10 14:43 UTC, PaulAnnekov commented on package.json
> +    "@elastic.io/object-storage-client": "^2.0.0",
https://www.notion.so/elasticio/Code-Style-89792419947546d2a52855d8df7a255b#0af15554a7d84cfcb52faaa9237281fa

2022-06-10 14:43 UTC, PaulAnnekov commented on lib/sailor.js
>          } catch (e) {
No need to catch it here at all. Will be caught by caller code.

2022-06-10 14:43 UTC, PaulAnnekov commented on lib/sailor.js
>                              logger.info('Message body not uploaded');
```suggestion
                            logger.error(e, 'Error during message/passthrough body upload');
```

2022-06-10 14:43 UTC, PaulAnnekov commented on lib/sailor.js
> +                            return onError(e);
```suggestion
                            return onError(new Error("Lightweight message/passthrough body upload error"));
```
This info will be enough for customer to see in errors. And additional details will be visible in logs.

2022-06-10 16:32 UTC, PaulAnnekov requested changes

2022-06-10 16:32 UTC, PaulAnnekov commented on package.json
> +    "@elastic.io/object-storage-client": "2.0.0",
version 2.0.0 has breaking change and test should fail in addAsStream. But 2.1.0 has reverted it. Use 2.1.0.

2022-06-14 07:44 UTC, irisked approved these changes

2022-06-15 15:38 UTC, PaulAnnekov approved these changes

2022-06-21 10:36 UTC, merged